### ISSUE TITLE
These links should be hyperlinks

### ISSUE THREAD

**Issue by qaisark** [muneeburrehman06/External-Css#2]
![image](https://user-images.githubusercontent.com/46220827/105176370-ff0fdc80-5b46-11eb-8f56-3dc2e85e4865.png)

**Comment by muneeburrehman06** [comment]
Done! These are already Hyper Links But I work more on it
![4](https://user-images.githubusercontent.com/77731443/105323356-d8f04800-5beb-11eb-99e3-ebf7da401647.png)
