### ISSUE TITLE
Add vertical space between degree information

### ISSUE THREAD

**Issue by qaisark** [muneeburrehman06/External-Css#3]
![image](https://user-images.githubusercontent.com/46220827/105176467-1c44ab00-5b47-11eb-8fab-c10d755a9487.png)

**Comment by muneeburrehman06** [comment]
Done
![3](https://user-images.githubusercontent.com/77731443/105323118-962e7000-5beb-11eb-91c1-6050451206e2.png)

**Comment by muneeburrehman06** [comment]
Done
![Screenshot (193)](https://user-images.githubusercontent.com/77731443/105337540-5a4fd680-5bfc-11eb-8d8c-ec35ba88bec2.png)
