### ISSUE TITLE
Fontstyle should be same (Here languages are Uppercase and simple-style & skills are lowercase and italic)

### ISSUE THREAD

**Issue by qaisark** [muneeburrehman06/External-Css#4]
![image](https://user-images.githubusercontent.com/46220827/105176657-53b35780-5b47-11eb-9605-dc2faba2f954.png)

**Comment by muneeburrehman06** [comment]
Done
![2](https://user-images.githubusercontent.com/77731443/105322010-0c31d780-5bea-11eb-9b07-1bdf0e64551e.png)

**Comment by muneeburrehman06** [comment]
Done
![2](https://user-images.githubusercontent.com/77731443/105322855-3c2daa80-5beb-11eb-96a2-6a3e78c0eb16.png)
